version: "3"

services:
  app:
    build: .
    user: 1000:1000
    container_name: multisportLogger
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 80:80
      - 443:443
    links:
      - db

  db:
    image: mysql:5.7.22
    environment:
      - MYSQL_ROOT_PASSWORD=${PASSWORD}
    volumes:
      - ./dbData:/var/lib/mysql

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      ports:
        - 127.0.0.8080:80
      environment:
        PMA_HOST: db
        MYSQL_ROOT_PASSWORD: ${PASSWORD}
      links:
        - db
